CREATE TABLE IF NOT EXISTS public.telegram_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_id BIGINT NOT NULL,
    message_id BIGINT,
    chat_id BIGINT,
    chat_title TEXT,
    chat_username TEXT,
    chat_type TEXT,
    sender_id BIGINT,
    sender_username TEXT,
    sender_first_name TEXT,
    sender_last_name TEXT,
    sender_is_bot BOOLEAN,
    sender_chat_id BIGINT,
    sender_chat_title TEXT,
    body TEXT,
    caption TEXT,
    message_type TEXT,
    sent_at_utc TIMESTAMPTZ,
    sent_date DATE,
    sent_time TIME,
    edited_at_utc TIMESTAMPTZ,
    reply_to_message_id BIGINT,
    forward_origin_json JSONB,
    entities_json JSONB,
    media_file_id TEXT,
    media_group_id TEXT,
    raw_payload_json JSONB NOT NULL,
    received_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(update_id, message_id)
);

CREATE INDEX IF NOT EXISTS telegram_messages_chat_id_idx
    ON public.telegram_messages(chat_id);

CREATE INDEX IF NOT EXISTS telegram_messages_sender_id_idx
    ON public.telegram_messages(sender_id);

CREATE INDEX IF NOT EXISTS telegram_messages_sent_at_utc_idx
    ON public.telegram_messages(sent_at_utc DESC);

CREATE INDEX IF NOT EXISTS telegram_messages_body_search_idx
    ON public.telegram_messages
    USING GIN (to_tsvector('simple', COALESCE(body, '') || ' ' || COALESCE(caption, '')));

ALTER TABLE public.telegram_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "telegram_messages_no_public_access" ON public.telegram_messages;
CREATE POLICY "telegram_messages_no_public_access"
    ON public.telegram_messages
    FOR ALL
    USING (false)
    WITH CHECK (false);
