CREATE TABLE IF NOT EXISTS public.telegram_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_id BIGINT NOT NULL,
    message_id BIGINT,
    chat_id BIGINT,
    chat_title TEXT,
    chat_username TEXT,
    chat_type TEXT,
    message_thread_id BIGINT,
    is_topic_message BOOLEAN,
    topic_name TEXT,
    topic_icon_color BIGINT,
    topic_icon_custom_emoji_id TEXT,
    sender_id BIGINT,
    sender_username TEXT,
    sender_first_name TEXT,
    sender_last_name TEXT,
    sender_is_bot BOOLEAN,
    sender_photo_file_id TEXT,
    sender_photo_file_unique_id TEXT,
    sender_chat_id BIGINT,
    sender_chat_title TEXT,
    body TEXT,
    caption TEXT,
    message_type TEXT,
    sent_at_utc TIMESTAMPTZ,
    sent_date DATE,
    sent_time TIME,
    edited_at_utc TIMESTAMPTZ,
    reply_to_message_id BIGINT,
    forward_origin_json JSONB,
    entities_json JSONB,
    media_file_id TEXT,
    media_group_id TEXT,
    raw_payload_json JSONB NOT NULL,
    received_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(update_id, message_id)
);

CREATE TABLE IF NOT EXISTS public.telegram_topics (
    chat_id BIGINT NOT NULL,
    message_thread_id BIGINT NOT NULL,
    topic_name TEXT,
    icon_color BIGINT,
    icon_custom_emoji_id TEXT,
    raw_payload_json JSONB,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (chat_id, message_thread_id)
);

CREATE TABLE IF NOT EXISTS public.telegram_chats (
    chat_id BIGINT PRIMARY KEY,
    chat_title TEXT,
    chat_username TEXT,
    chat_type TEXT,
    joined_at_utc TIMESTAMPTZ,
    first_seen_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    raw_payload_json JSONB,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.telegram_message_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    user_id BIGINT,
    actor_chat_id BIGINT,
    reaction_type TEXT NOT NULL,
    reaction_emoji TEXT,
    custom_emoji_id TEXT,
    reaction_json JSONB NOT NULL,
    user_username TEXT,
    user_first_name TEXT,
    user_last_name TEXT,
    user_photo_file_id TEXT,
    user_photo_file_unique_id TEXT,
    reacted_at_utc TIMESTAMPTZ,
    raw_payload_json JSONB NOT NULL,
    received_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.telegram_messages
    ADD COLUMN IF NOT EXISTS message_thread_id BIGINT,
    ADD COLUMN IF NOT EXISTS is_topic_message BOOLEAN,
    ADD COLUMN IF NOT EXISTS topic_name TEXT,
    ADD COLUMN IF NOT EXISTS topic_icon_color BIGINT,
    ADD COLUMN IF NOT EXISTS topic_icon_custom_emoji_id TEXT,
    ADD COLUMN IF NOT EXISTS sender_photo_file_id TEXT,
    ADD COLUMN IF NOT EXISTS sender_photo_file_unique_id TEXT;

CREATE INDEX IF NOT EXISTS telegram_messages_chat_id_idx
    ON public.telegram_messages(chat_id);

CREATE INDEX IF NOT EXISTS telegram_messages_sender_id_idx
    ON public.telegram_messages(sender_id);

CREATE INDEX IF NOT EXISTS telegram_messages_sent_at_utc_idx
    ON public.telegram_messages(sent_at_utc DESC);

CREATE INDEX IF NOT EXISTS telegram_messages_thread_idx
    ON public.telegram_messages(chat_id, message_thread_id);

CREATE INDEX IF NOT EXISTS telegram_messages_body_search_idx
    ON public.telegram_messages
    USING GIN (to_tsvector('simple', COALESCE(body, '') || ' ' || COALESCE(caption, '')));

CREATE INDEX IF NOT EXISTS telegram_message_reactions_message_idx
    ON public.telegram_message_reactions(chat_id, message_id);

CREATE INDEX IF NOT EXISTS telegram_message_reactions_user_idx
    ON public.telegram_message_reactions(user_id);

INSERT INTO public.telegram_chats (
    chat_id,
    chat_title,
    chat_username,
    chat_type,
    joined_at_utc,
    first_seen_at_utc,
    last_seen_at_utc,
    updated_at_utc
)
SELECT DISTINCT ON (chat_id)
    chat_id,
    chat_title,
    chat_username,
    chat_type,
    MIN(received_at_utc) OVER (PARTITION BY chat_id),
    MIN(received_at_utc) OVER (PARTITION BY chat_id),
    MAX(received_at_utc) OVER (PARTITION BY chat_id),
    NOW()
FROM public.telegram_messages
WHERE chat_id IS NOT NULL
ORDER BY chat_id, received_at_utc DESC
ON CONFLICT (chat_id) DO NOTHING;

CREATE OR REPLACE VIEW public.telegram_group_stats AS
SELECT
    c.chat_id,
    c.chat_title,
    c.chat_username,
    c.chat_type,
    c.joined_at_utc,
    c.first_seen_at_utc,
    c.last_seen_at_utc,
    COUNT(m.id)::BIGINT AS message_count,
    MAX(m.sent_at_utc) AS last_message_at_utc
FROM public.telegram_chats c
LEFT JOIN public.telegram_messages m ON m.chat_id = c.chat_id
GROUP BY
    c.chat_id,
    c.chat_title,
    c.chat_username,
    c.chat_type,
    c.joined_at_utc,
    c.first_seen_at_utc,
    c.last_seen_at_utc;

ALTER TABLE public.telegram_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telegram_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telegram_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telegram_message_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "telegram_messages_no_public_access" ON public.telegram_messages;
CREATE POLICY "telegram_messages_no_public_access"
    ON public.telegram_messages
    FOR ALL
    USING (false)
    WITH CHECK (false);

DROP POLICY IF EXISTS "telegram_topics_no_public_access" ON public.telegram_topics;
CREATE POLICY "telegram_topics_no_public_access"
    ON public.telegram_topics
    FOR ALL
    USING (false)
    WITH CHECK (false);

DROP POLICY IF EXISTS "telegram_chats_no_public_access" ON public.telegram_chats;
CREATE POLICY "telegram_chats_no_public_access"
    ON public.telegram_chats
    FOR ALL
    USING (false)
    WITH CHECK (false);

DROP POLICY IF EXISTS "telegram_message_reactions_no_public_access" ON public.telegram_message_reactions;
CREATE POLICY "telegram_message_reactions_no_public_access"
    ON public.telegram_message_reactions
    FOR ALL
    USING (false)
    WITH CHECK (false);
