CREATE TABLE IF NOT EXISTS public.visibility_access_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at_utc TIMESTAMPTZ,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT visibility_access_users_email_domain_chk
        CHECK (email = lower(email) AND email ~ '^[^@\s]+@toman\.ir$')
);

CREATE INDEX IF NOT EXISTS visibility_access_users_email_idx
    ON public.visibility_access_users(email);

ALTER TABLE public.visibility_access_users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "visibility_access_users_no_public_access" ON public.visibility_access_users;
CREATE POLICY "visibility_access_users_no_public_access"
    ON public.visibility_access_users
    FOR ALL
    USING (false)
    WITH CHECK (false);
