CREATE TABLE IF NOT EXISTS public.telegram_message_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    user_id BIGINT,
    actor_chat_id BIGINT,
    reaction_type TEXT NOT NULL,
    reaction_emoji TEXT,
    custom_emoji_id TEXT,
    reaction_json JSONB NOT NULL,
    user_username TEXT,
    user_first_name TEXT,
    user_last_name TEXT,
    user_photo_file_id TEXT,
    user_photo_file_unique_id TEXT,
    reacted_at_utc TIMESTAMPTZ,
    raw_payload_json JSONB NOT NULL,
    received_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS telegram_message_reactions_message_idx
    ON public.telegram_message_reactions(chat_id, message_id);

CREATE INDEX IF NOT EXISTS telegram_message_reactions_user_idx
    ON public.telegram_message_reactions(user_id);

ALTER TABLE public.telegram_message_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "telegram_message_reactions_no_public_access" ON public.telegram_message_reactions;
CREATE POLICY "telegram_message_reactions_no_public_access"
    ON public.telegram_message_reactions
    FOR ALL
    USING (false)
    WITH CHECK (false);
