CREATE TABLE IF NOT EXISTS public.visibility_roadmap_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (length(btrim(title)) BETWEEN 2 AND 180),
    description TEXT NOT NULL DEFAULT '',
    owner_email TEXT NOT NULL CHECK (owner_email ~* '^[^@\s]+@toman\.ir$'),
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    status TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'in_progress', 'delivered', 'blocked', 'canceled')),
    delivery_date DATE NOT NULL,
    created_by_email TEXT,
    updated_by_email TEXT,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS visibility_roadmap_items_delivery_date_idx
    ON public.visibility_roadmap_items (delivery_date ASC);

CREATE INDEX IF NOT EXISTS visibility_roadmap_items_status_idx
    ON public.visibility_roadmap_items (status);

CREATE INDEX IF NOT EXISTS visibility_roadmap_items_priority_idx
    ON public.visibility_roadmap_items (priority);

ALTER TABLE public.visibility_roadmap_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS visibility_roadmap_items_no_public_access ON public.visibility_roadmap_items;

CREATE POLICY visibility_roadmap_items_no_public_access
    ON public.visibility_roadmap_items
    FOR ALL
    USING (false)
    WITH CHECK (false);

ALTER TABLE public.visibility_access_audit_logs
    DROP CONSTRAINT IF EXISTS visibility_access_audit_logs_action_chk;

ALTER TABLE public.visibility_access_audit_logs
    ADD CONSTRAINT visibility_access_audit_logs_action_chk
    CHECK (
        action IN (
            'invite',
            'permissions_update',
            'revoke',
            'reactivate',
            'password_change',
            'password_recovery',
            'invite_email',
            'resend_invite',
            'profile_update',
            'bot_create',
            'bot_rotate',
            'group_broadcast',
            'group_access_update',
            'group_label_update',
            'sender_label_update',
            'thread_reply',
            'roadmap_create',
            'roadmap_update'
        )
    );
