CREATE TABLE IF NOT EXISTS public.visibility_access_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email TEXT,
    target_email TEXT,
    action TEXT NOT NULL,
    old_values JSONB NOT NULL DEFAULT '{}'::jsonb,
    new_values JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT visibility_access_audit_logs_action_chk
        CHECK (action IN ('invite', 'permissions_update', 'revoke', 'reactivate', 'password_change'))
);

CREATE INDEX IF NOT EXISTS visibility_access_audit_logs_created_idx
    ON public.visibility_access_audit_logs(created_at_utc DESC);

CREATE INDEX IF NOT EXISTS visibility_access_audit_logs_actor_idx
    ON public.visibility_access_audit_logs(actor_email);

CREATE INDEX IF NOT EXISTS visibility_access_audit_logs_target_idx
    ON public.visibility_access_audit_logs(target_email);

ALTER TABLE public.visibility_access_audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "visibility_access_audit_logs_no_public_access" ON public.visibility_access_audit_logs;
CREATE POLICY "visibility_access_audit_logs_no_public_access"
    ON public.visibility_access_audit_logs
    FOR ALL
    USING (false)
    WITH CHECK (false);
