ALTER TABLE public.visibility_roadmap_items
    ADD COLUMN IF NOT EXISTS item_type TEXT NOT NULL DEFAULT 'delivery',
    ADD COLUMN IF NOT EXISTS progress SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS risk TEXT NOT NULL DEFAULT 'medium',
    ADD COLUMN IF NOT EXISTS initiative_id BIGINT REFERENCES public.visibility_roadmap_items(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS major_delivery_id BIGINT REFERENCES public.visibility_roadmap_items(id) ON DELETE SET NULL;

ALTER TABLE public.visibility_roadmap_items
    DROP CONSTRAINT IF EXISTS visibility_roadmap_items_item_type_chk,
    ADD CONSTRAINT visibility_roadmap_items_item_type_chk
        CHECK (item_type IN ('initiative', 'major', 'delivery'));

ALTER TABLE public.visibility_roadmap_items
    DROP CONSTRAINT IF EXISTS visibility_roadmap_items_progress_chk,
    ADD CONSTRAINT visibility_roadmap_items_progress_chk
        CHECK (progress BETWEEN 0 AND 100);

ALTER TABLE public.visibility_roadmap_items
    DROP CONSTRAINT IF EXISTS visibility_roadmap_items_risk_chk,
    ADD CONSTRAINT visibility_roadmap_items_risk_chk
        CHECK (risk IN ('low', 'medium', 'high', 'critical'));

ALTER TABLE public.visibility_roadmap_items
    DROP CONSTRAINT IF EXISTS visibility_roadmap_items_status_check;

ALTER TABLE public.visibility_roadmap_items
    DROP CONSTRAINT IF EXISTS visibility_roadmap_items_status_chk;

UPDATE public.visibility_roadmap_items
SET status = CASE status
    WHEN 'planned' THEN 'not_started'
    WHEN 'in_progress' THEN 'on_track'
    WHEN 'delivered' THEN 'delivered'
    WHEN 'blocked' THEN 'blocked'
    WHEN 'canceled' THEN 'canceled'
    ELSE status
END
WHERE status IN ('planned', 'in_progress', 'delivered', 'blocked', 'canceled');

ALTER TABLE public.visibility_roadmap_items
    ADD CONSTRAINT visibility_roadmap_items_status_chk
        CHECK (status IN ('not_started', 'on_track', 'at_risk', 'blocked', 'delivered', 'canceled'));

ALTER TABLE public.visibility_roadmap_items
    ALTER COLUMN status SET DEFAULT 'not_started';

CREATE INDEX IF NOT EXISTS visibility_roadmap_items_item_type_idx
    ON public.visibility_roadmap_items (item_type);

CREATE INDEX IF NOT EXISTS visibility_roadmap_items_initiative_idx
    ON public.visibility_roadmap_items (initiative_id);

CREATE INDEX IF NOT EXISTS visibility_roadmap_items_major_delivery_idx
    ON public.visibility_roadmap_items (major_delivery_id);

CREATE TABLE IF NOT EXISTS public.visibility_roadmap_dependencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_roadmap_id BIGINT NOT NULL REFERENCES public.visibility_roadmap_items(id) ON DELETE CASCADE,
    consumer_roadmap_id BIGINT NOT NULL REFERENCES public.visibility_roadmap_items(id) ON DELETE CASCADE,
    need_by_date DATE,
    need_by_month SMALLINT,
    need_by_week SMALLINT,
    expected_delivery_date DATE,
    expected_delivery_month SMALLINT,
    expected_delivery_week SMALLINT,
    dependency_status TEXT NOT NULL DEFAULT 'on_track',
    description TEXT NOT NULL DEFAULT '',
    created_by_email TEXT,
    updated_by_email TEXT,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT visibility_roadmap_dependencies_not_self_chk
        CHECK (provider_roadmap_id <> consumer_roadmap_id),
    CONSTRAINT visibility_roadmap_dependencies_need_month_chk
        CHECK (need_by_month IS NULL OR need_by_month BETWEEN 6 AND 12),
    CONSTRAINT visibility_roadmap_dependencies_need_week_chk
        CHECK (need_by_week IS NULL OR need_by_week BETWEEN 1 AND 4),
    CONSTRAINT visibility_roadmap_dependencies_expected_month_chk
        CHECK (expected_delivery_month IS NULL OR expected_delivery_month BETWEEN 6 AND 12),
    CONSTRAINT visibility_roadmap_dependencies_expected_week_chk
        CHECK (expected_delivery_week IS NULL OR expected_delivery_week BETWEEN 1 AND 4),
    CONSTRAINT visibility_roadmap_dependencies_status_chk
        CHECK (dependency_status IN ('not_started', 'on_track', 'at_risk', 'blocked', 'delivered')),
    UNIQUE (provider_roadmap_id, consumer_roadmap_id)
);

CREATE INDEX IF NOT EXISTS visibility_roadmap_dependencies_provider_idx
    ON public.visibility_roadmap_dependencies (provider_roadmap_id);

CREATE INDEX IF NOT EXISTS visibility_roadmap_dependencies_consumer_idx
    ON public.visibility_roadmap_dependencies (consumer_roadmap_id);

ALTER TABLE public.visibility_roadmap_dependencies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS visibility_roadmap_dependencies_no_public_access ON public.visibility_roadmap_dependencies;

CREATE POLICY visibility_roadmap_dependencies_no_public_access
    ON public.visibility_roadmap_dependencies
    FOR ALL
    USING (false)
    WITH CHECK (false);

INSERT INTO public.visibility_roadmap_dependencies (
    provider_roadmap_id,
    consumer_roadmap_id,
    need_by_date,
    need_by_month,
    need_by_week,
    expected_delivery_date,
    expected_delivery_month,
    expected_delivery_week,
    dependency_status,
    description,
    created_by_email,
    updated_by_email
)
SELECT
    child.id,
    parent.id,
    parent.delivery_date,
    parent.delivery_month,
    parent.delivery_week,
    child.delivery_date,
    child.delivery_month,
    child.delivery_week,
    CASE
        WHEN child.status = 'blocked' THEN 'blocked'
        WHEN child.status = 'delivered' THEN 'delivered'
        WHEN child.delivery_date > parent.delivery_date THEN 'at_risk'
        ELSE 'on_track'
    END,
    child.description,
    child.created_by_email,
    child.updated_by_email
FROM public.visibility_roadmap_items child
JOIN public.visibility_roadmap_items parent ON parent.id = child.parent_roadmap_id
ON CONFLICT (provider_roadmap_id, consumer_roadmap_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.visibility_roadmap_checkpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_item_id BIGINT NOT NULL REFERENCES public.visibility_roadmap_items(id) ON DELETE CASCADE,
    title TEXT NOT NULL CHECK (length(btrim(title)) BETWEEN 2 AND 180),
    expected_date DATE,
    expected_month SMALLINT,
    expected_week SMALLINT,
    status TEXT NOT NULL DEFAULT 'not_started',
    created_by_email TEXT,
    updated_by_email TEXT,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT visibility_roadmap_checkpoints_month_chk
        CHECK (expected_month IS NULL OR expected_month BETWEEN 6 AND 12),
    CONSTRAINT visibility_roadmap_checkpoints_week_chk
        CHECK (expected_week IS NULL OR expected_week BETWEEN 1 AND 4),
    CONSTRAINT visibility_roadmap_checkpoints_status_chk
        CHECK (status IN ('not_started', 'on_track', 'at_risk', 'blocked', 'delivered'))
);

CREATE INDEX IF NOT EXISTS visibility_roadmap_checkpoints_item_idx
    ON public.visibility_roadmap_checkpoints (roadmap_item_id);

ALTER TABLE public.visibility_roadmap_checkpoints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS visibility_roadmap_checkpoints_no_public_access ON public.visibility_roadmap_checkpoints;

CREATE POLICY visibility_roadmap_checkpoints_no_public_access
    ON public.visibility_roadmap_checkpoints
    FOR ALL
    USING (false)
    WITH CHECK (false);
