CREATE TABLE IF NOT EXISTS public.visibility_user_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (length(btrim(name)) BETWEEN 2 AND 120),
    description TEXT NOT NULL DEFAULT '',
    created_by_email TEXT,
    updated_by_email TEXT,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.visibility_user_group_members (
    group_id BIGINT NOT NULL REFERENCES public.visibility_user_groups(id) ON DELETE CASCADE,
    user_email TEXT NOT NULL REFERENCES public.visibility_access_users(email) ON DELETE CASCADE,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (group_id, user_email)
);

CREATE INDEX IF NOT EXISTS visibility_user_group_members_user_email_idx
    ON public.visibility_user_group_members (user_email);

ALTER TABLE public.visibility_user_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visibility_user_group_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS visibility_user_groups_no_public_access ON public.visibility_user_groups;
CREATE POLICY visibility_user_groups_no_public_access
    ON public.visibility_user_groups
    FOR ALL
    USING (false)
    WITH CHECK (false);

DROP POLICY IF EXISTS visibility_user_group_members_no_public_access ON public.visibility_user_group_members;
CREATE POLICY visibility_user_group_members_no_public_access
    ON public.visibility_user_group_members
    FOR ALL
    USING (false)
    WITH CHECK (false);

ALTER TABLE public.visibility_access_audit_logs
    DROP CONSTRAINT IF EXISTS visibility_access_audit_logs_action_chk;

ALTER TABLE public.visibility_access_audit_logs
    ADD CONSTRAINT visibility_access_audit_logs_action_chk
    CHECK (
        action IN (
            'invite',
            'permissions_update',
            'revoke',
            'reactivate',
            'password_change',
            'password_recovery',
            'invite_email',
            'resend_invite',
            'profile_update',
            'bot_create',
            'bot_rotate',
            'group_broadcast',
            'group_access_update',
            'group_label_update',
            'sender_label_update',
            'thread_reply',
            'roadmap_create',
            'roadmap_update',
            'user_group_create',
            'user_group_update',
            'user_group_delete'
        )
    );
